Article ansible devops for itops
danacton/practices-of-mastery pull request #11
Opened 2016-10-07 11:46 UTC by f3218694

Please review and advise. I will like to do a more technical follow up.

2016-10-07 13:48 UTC, danacton requested changes

2016-10-07 13:48 UTC, danacton commented on article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> +The following article is based on my experience as a middelware"IT Ops guys" and the benefits of Ansible.
Add a space after middleware

2016-10-07 13:48 UTC, danacton commented on article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> +Ansible is different to other automation tools like Chef, Puppet and Salt. The main difference is that Ansible is first a push tool rather than a pull. In now way are the other tools mentioned inferi
- "In no way" rather than "In now way"
- "easier transision" -> "easier transition"

2016-10-07 13:48 UTC, danacton commented on article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> +*Whats cool about Ansible?* Easy...you write stuff in YAML and Jinja2, which is so easy to learn my 3 year old daughter could write an Ansible playbook. You can do orcestraction from your laptop to y
- orchestration
- python

2016-10-07 13:48 UTC, danacton commented on article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> +**Whats bad about Ansible?** In my opinion...the documentation on the Ansible website. There docs are unecessarily complicated (for an IT Ops guy) especially some of the examples. But you quickly lea
- What's not What's
- "Their docs" not "there docs"
- unnecessarily

2016-10-07 13:48 UTC, danacton commented on article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> +**What can Ansible do?** .....anything..... Well it cant make you carrot juice in the morning but you know what I mean. Any task that needs orcestration and automation.
- can't
- orchestration

2016-10-07 13:48 UTC, danacton commented on article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> +**Why should Ansible be my entry into DevOps?** The Ansible path will quickly teach you how awesome it is to automate every repeatable task you have ever had. As an IT Ops guys I know that we love wr
- version controlled

2016-10-07 13:48 UTC, danacton commented on article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> +Install ansible. You can do this serveral ways here are a few;
- here is one

2016-10-07 13:48 UTC, danacton commented on article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> +One of the biggest questions I had when researching Ansible was that, if it was so flexible and so cool why wasnt there an easy example of creating a playbook that diffreniated between all the test e
- wasn't
- differentiated
- to the that -> to that
- It's
- somemany many to this -> so many ways to do this (I think?)
- shouldn't

2017-03-30 11:49 UTC, f3218694 commented
Hi Dan

I was forced on leave so I actually had to time to correct all my mistakes.
At least now I know quality of articles that you are looking for. Thanks
for going through all the mistakes. Sorry again for not getting to this
sooner.

regards
Reagan

On Fri, Oct 7, 2016 at 3:48 PM, Daniel Acton <notifications@github.com>
wrote:

> *@danacton* requested changes on this pull request.
> ------------------------------
>
> In article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> <https://github.com/danacton/practices-of-mastery/pull/11#pullrequestreview-3302941>
> :
>
> > @@ -0,0 +1,32 @@
> +#**Ansible: DevOps for IT Ops**
> +
> +The following article is based on my experience as a middelware"IT Ops guys" and the benefits of Ansible.
>
> Add a space after middleware
> ------------------------------
>
> In article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> <https://github.com/danacton/practices-of-mastery/pull/11#pullrequestreview-3302941>
> :
>
> > @@ -0,0 +1,32 @@
> +#**Ansible: DevOps for IT Ops**
> +
> +The following article is based on my experience as a middelware"IT Ops guys" and the benefits of Ansible.
> +
> +##**Background**
> +Ansible is different to other automation tools like Chef, Puppet and Salt. The main difference is that Ansible is first a push tool rather than a pull. In now way are the other tools mentioned inferior but Ansible offers an easier transision from no automation to fully automated.
>
>
>    - "In no way" rather than "In now way"
>    - "easier transision" -> "easier transition"
>
> ------------------------------
>
> In article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> <https://github.com/danacton/practices-of-mastery/pull/11#pullrequestreview-3302941>
> :
>
> > @@ -0,0 +1,32 @@
> +#**Ansible: DevOps for IT Ops**
> +
> +The following article is based on my experience as a middelware"IT Ops guys" and the benefits of Ansible.
> +
> +##**Background**
> +Ansible is different to other automation tools like Chef, Puppet and Salt. The main difference is that Ansible is first a push tool rather than a pull. In now way are the other tools mentioned inferior but Ansible offers an easier transision from no automation to fully automated.
> +
> +##**The Ansible awakening**
> +*Whats cool about Ansible?* Easy...you write stuff in YAML and Jinja2, which is so easy to learn my 3 year old daughter could write an Ansible playbook. You can do orcestraction from your laptop to your target servers without installing any additional software (As long as ssh and phython is installed).
>
>
>    - orchestration
>    - python
>
> ------------------------------
>
> In article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> <https://github.com/danacton/practices-of-mastery/pull/11#pullrequestreview-3302941>
> :
>
> > @@ -0,0 +1,32 @@
> +#**Ansible: DevOps for IT Ops**
> +
> +The following article is based on my experience as a middelware"IT Ops guys" and the benefits of Ansible.
> +
> +##**Background**
> +Ansible is different to other automation tools like Chef, Puppet and Salt. The main difference is that Ansible is first a push tool rather than a pull. In now way are the other tools mentioned inferior but Ansible offers an easier transision from no automation to fully automated.
> +
> +##**The Ansible awakening**
> +*Whats cool about Ansible?* Easy...you write stuff in YAML and Jinja2, which is so easy to learn my 3 year old daughter could write an Ansible playbook. You can do orcestraction from your laptop to your target servers without installing any additional software (As long as ssh and phython is installed).
> +
> +**Whats bad about Ansible?** In my opinion...the documentation on the Ansible website. There docs are unecessarily complicated (for an IT Ops guy) especially some of the examples. But you quickly learn to "decrypt" it.
>
>
>    - What's not What's
>    - "Their docs" not "there docs"
>    - unnecessarily
>
> ------------------------------
>
> In article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> <https://github.com/danacton/practices-of-mastery/pull/11#pullrequestreview-3302941>
> :
>
> > @@ -0,0 +1,32 @@
> +#**Ansible: DevOps for IT Ops**
> +
> +The following article is based on my experience as a middelware"IT Ops guys" and the benefits of Ansible.
> +
> +##**Background**
> +Ansible is different to other automation tools like Chef, Puppet and Salt. The main difference is that Ansible is first a push tool rather than a pull. In now way are the other tools mentioned inferior but Ansible offers an easier transision from no automation to fully automated.
> +
> +##**The Ansible awakening**
> +*Whats cool about Ansible?* Easy...you write stuff in YAML and Jinja2, which is so easy to learn my 3 year old daughter could write an Ansible playbook. You can do orcestraction from your laptop to your target servers without installing any additional software (As long as ssh and phython is installed).
> +
> +**Whats bad about Ansible?** In my opinion...the documentation on the Ansible website. There docs are unecessarily complicated (for an IT Ops guy) especially some of the examples. But you quickly learn to "decrypt" it.
> +
> +**What can Ansible do?** .....anything..... Well it cant make you carrot juice in the morning but you know what I mean. Any task that needs orcestration and automation.
>
>
>    - can't
>    - orchestration
>
> ------------------------------
>
> In article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> <https://github.com/danacton/practices-of-mastery/pull/11#pullrequestreview-3302941>
> :
>
> > +
> +##**Background**
> +Ansible is different to other automation tools like Chef, Puppet and Salt. The main difference is that Ansible is first a push tool rather than a pull. In now way are the other tools mentioned inferior but Ansible offers an easier transision from no automation to fully automated.
> +
> +##**The Ansible awakening**
> +*Whats cool about Ansible?* Easy...you write stuff in YAML and Jinja2, which is so easy to learn my 3 year old daughter could write an Ansible playbook. You can do orcestraction from your laptop to your target servers without installing any additional software (As long as ssh and phython is installed).
> +
> +**Whats bad about Ansible?** In my opinion...the documentation on the Ansible website. There docs are unecessarily complicated (for an IT Ops guy) especially some of the examples. But you quickly learn to "decrypt" it.
> +
> +**What can Ansible do?** .....anything..... Well it cant make you carrot juice in the morning but you know what I mean. Any task that needs orcestration and automation.
> +
> +**How does Ansible work?** By default it connects to your target machine via ssh (hopefully in your case using an ssh key that you have exchanged). It then runs your tasks that you have listed. Sounds easy but once you work through the concepts of roles, tasks, plays, playbooks and variables, you will realize that it is that simple.
> +
> +**Will it work on Windows** Yes :(  (Im not a big windows fan)
> +
> +**Why should Ansible be my entry into DevOps?** The Ansible path will quickly teach you how awesome it is to automate every repeatable task you have ever had. As an IT Ops guys I know that we love writing scripts and popping them into the crontab. If you want you can still have your scripts in a verion controlled repo which Ansible will deploy and add to the crontab for you.
>
>
>    - version controlled
>
> ------------------------------
>
> In article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> <https://github.com/danacton/practices-of-mastery/pull/11#pullrequestreview-3302941>
> :
>
> > +
> +##**The Ansible awakening**
> +*Whats cool about Ansible?* Easy...you write stuff in YAML and Jinja2, which is so easy to learn my 3 year old daughter could write an Ansible playbook. You can do orcestraction from your laptop to your target servers without installing any  [...]

2017-04-03 19:59 UTC, danacton approved these changes

2017-04-03 19:59 UTC, merged

2017-04-03 20:00 UTC, danacton commented
No worries. I've merged the changes. How do you want to be attributed? Have
a look at http://www.practicesofmastery.com/contributors/ for examples.

On Thu, Mar 30, 2017 at 1:49 PM, f3218694 <notifications@github.com> wrote:

> Hi Dan
>
> I was forced on leave so I actually had to time to correct all my mistakes.
> At least now I know quality of articles that you are looking for. Thanks
> for going through all the mistakes. Sorry again for not getting to this
> sooner.
>
> regards
> Reagan
>
> On Fri, Oct 7, 2016 at 3:48 PM, Daniel Acton <notifications@github.com>
> wrote:
>
> > *@danacton* requested changes on this pull request.
> > ------------------------------
> >
> > In article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> > <https://github.com/danacton/practices-of-mastery/pull/11#
> pullrequestreview-3302941>
> > :
> >
> > > @@ -0,0 +1,32 @@
> > +#**Ansible: DevOps for IT Ops**
> > +
> > +The following article is based on my experience as a middelware"IT Ops
> guys" and the benefits of Ansible.
> >
> > Add a space after middleware
> > ------------------------------
> >
> > In article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> > <https://github.com/danacton/practices-of-mastery/pull/11#
> pullrequestreview-3302941>
> > :
> >
> > > @@ -0,0 +1,32 @@
> > +#**Ansible: DevOps for IT Ops**
> > +
> > +The following article is based on my experience as a middelware"IT Ops
> guys" and the benefits of Ansible.
> > +
> > +##**Background**
> > +Ansible is different to other automation tools like Chef, Puppet and
> Salt. The main difference is that Ansible is first a push tool rather than
> a pull. In now way are the other tools mentioned inferior but Ansible
> offers an easier transision from no automation to fully automated.
> >
> >
> > - "In no way" rather than "In now way"
> > - "easier transision" -> "easier transition"
> >
> > ------------------------------
> >
> > In article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> > <https://github.com/danacton/practices-of-mastery/pull/11#
> pullrequestreview-3302941>
> > :
> >
> > > @@ -0,0 +1,32 @@
> > +#**Ansible: DevOps for IT Ops**
> > +
> > +The following article is based on my experience as a middelware"IT Ops
> guys" and the benefits of Ansible.
> > +
> > +##**Background**
> > +Ansible is different to other automation tools like Chef, Puppet and
> Salt. The main difference is that Ansible is first a push tool rather than
> a pull. In now way are the other tools mentioned inferior but Ansible
> offers an easier transision from no automation to fully automated.
> > +
> > +##**The Ansible awakening**
> > +*Whats cool about Ansible?* Easy...you write stuff in YAML and Jinja2,
> which is so easy to learn my 3 year old daughter could write an Ansible
> playbook. You can do orcestraction from your laptop to your target servers
> without installing any additional software (As long as ssh and phython is
> installed).
> >
> >
> > - orchestration
> > - python
> >
> > ------------------------------
> >
> > In article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> > <https://github.com/danacton/practices-of-mastery/pull/11#
> pullrequestreview-3302941>
> > :
> >
> > > @@ -0,0 +1,32 @@
> > +#**Ansible: DevOps for IT Ops**
> > +
> > +The following article is based on my experience as a middelware"IT Ops
> guys" and the benefits of Ansible.
> > +
> > +##**Background**
> > +Ansible is different to other automation tools like Chef, Puppet and
> Salt. The main difference is that Ansible is first a push tool rather than
> a pull. In now way are the other tools mentioned inferior but Ansible
> offers an easier transision from no automation to fully automated.
> > +
> > +##**The Ansible awakening**
> > +*Whats cool about Ansible?* Easy...you write stuff in YAML and Jinja2,
> which is so easy to learn my 3 year old daughter could write an Ansible
> playbook. You can do orcestraction from your laptop to your target servers
> without installing any additional software (As long as ssh and phython is
> installed).
> > +
> > +**Whats bad about Ansible?** In my opinion...the documentation on the
> Ansible website. There docs are unecessarily complicated (for an IT Ops
> guy) especially some of the examples. But you quickly learn to "decrypt" it.
> >
> >
> > - What's not What's
> > - "Their docs" not "there docs"
> > - unnecessarily
> >
> > ------------------------------
> >
> > In article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> > <https://github.com/danacton/practices-of-mastery/pull/11#
> pullrequestreview-3302941>
> > :
> >
> > > @@ -0,0 +1,32 @@
> > +#**Ansible: DevOps for IT Ops**
> > +
> > +The following article is based on my experience as a middelware"IT Ops
> guys" and the benefits of Ansible.
> > +
> > +##**Background**
> > +Ansible is different to other automation tools like Chef, Puppet and
> Salt. The main difference is that Ansible is first a push tool rather than
> a pull. In now way are the other tools mentioned inferior but Ansible
> offers an easier transision from no automation to fully automated.
> > +
> > +##**The Ansible awakening**
> > +*Whats cool about Ansible?* Easy...you write stuff in YAML and Jinja2,
> which is so easy to learn my 3 year old daughter could write an Ansible
> playbook. You can do orcestraction from your laptop to your target servers
> without installing any additional software (As long as ssh and phython is
> installed).
> > +
> > +**Whats bad about Ansible?** In my opinion...the documentation on the
> Ansible website. There docs are unecessarily complicated (for an IT Ops
> guy) especially some of the examples. But you quickly learn to "decrypt" it.
> > +
> > +**What can Ansible do?** .....anything..... Well it cant make you
> carrot juice in the morning but you know what I mean. Any task that needs
> orcestration and automation.
> >
> >
> > - can't
> > - orchestration
> >
> > ------------------------------
> >
> > In article-ansible-devops-for-itops/article-ansible-devops-for-itops.md
> > <https://github.com/danacton/practices-of-mastery/pull/11#
> pullrequestreview-3302941>
> > :
> >
> > > +
> > +##**Background**
> > +Ansible is different to other automation tools like Chef, Puppet and
> Salt. The main difference is that Ansible is first a push tool rather than
> a pull. In now way are the other tools mentioned inferior but Ansible
> offers an easier transision from no automation to fully automated.
> > +
> > +##**The Ansible awakening**
> > +*Whats cool about Ansible?* Easy...you write stuff in YAML and Jinja2,
> which is so easy to learn my 3 year old daughter could write an Ansible
> playbook. You can do orcestraction from your laptop to your target servers
> without installing any additional software (As long as ssh and phython is
> installed).
> > +
> > +**Whats bad about Ansible?** In my opinion...the documentation on the
> Ansible website. There docs are unecessarily complicated (for an IT Ops
> guy) especially some of the examples. But you quickly learn to "decrypt" it.
> > +
> > +**What can Ansible do?** .....anything..... Well it cant make you
> carrot juice in the morning but you know what I mean. Any task that needs
> orcestration and automation.
> > +
> > +**How does Ansible work?** By default it connects to your target
> machine via ssh (hopefully in your case using an ssh key that you have
> exchanged). It then runs your tasks that you have listed. Sounds easy but
> once you work through the concepts of roles, tasks, plays, playbooks and
> variables, you will realize that it is that simple.
> > +
> > +**Will it work on Windows** Yes :( (Im not a big windows fan)
> > +
> > +**Why should Ansible be my entry into DevOps?** The Ansible path will
> quickly teach you how awesome it is to automate every repeatable task you
> have ever had. As an IT Ops guys I know that we love writing scripts and
> popping them into the crontab. If you want you can still have your scripts
> in a veri [...]